### ISSUE TITLE
HTML init() function breaks after setting custom params

### ISSUE THREAD

**Issue by Tredde** [jenky/laravel-plupload#1]
First of all a big thank you for this awesome package.

When playing around with the setting I discovered that when using setCustomParams throught the Plupload::make, the HTML init() function breaks.

This is because in the init() function you start with if(!$this->data). And because I used the setCustomParams function $this-data is filled before calling init().

Upon bypassing the if statement in the init() function, everything works fine again. And the custom param is added to the data.

Maybe you can update the init() function?

Greetz Erik

**Comment by jenky** [comment]
Updated in f0f9d34. Thanks.
